name: deploy music information notifier

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_SESSION_TOKEN: ${{secrets.AWS_SESSION_TOKEN}}
      AWS_REGION: eu-central-1
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      # create bucket because sandbox maybe destroy the bucket
      - name: setup terraform s3 state bucket
        run: |
          cd infrastructure
          sh setup_terraform_state_s3_bucket.sh
      - name: build source code
        run: |
          cd src
          sh build_source_code.sh
      - name: deploy with terraform
        env:
          API_CLIENT_ID: ${{secrets.API_CLIENT_ID}}
          API_CLIENT_SECRET: ${{secrets.API_CLIENT_SECRET}}
        run: |
          cd infrastructure
          terraform init
          terraform apply -var="api_client_id=$API_CLIENT_ID" -var="api_client_secret=$API_CLIENT_SECRET" -auto-approve
